### ISSUE TITLE
Crashing on a Mac M1 Max

### ISSUE THREAD

**Issue by humanplugged** [Sorcerio/MBM-Music-Visualizer#3]
Hey Sorcerio.

MBM crashes once i run it, and gives this error:  libc++abi: terminating due to uncaught exception of type nsexception

I did a lot of research but couldn't find any solution/workaround for it. 

Audioscheduler nodes also gives the same error.

Any help would be grateful.

Best

**Comment by Sorcerio** [comment]
Hey, please use the Issue Template when submitting issues.

Without additional logs (like what ComfyUI gives you on screen when it crashes), it's very difficult to diagnose a problem. However, since you're also having issues with the `AudioScheduler` node which also uses `matplotlib` the issue is likely from there. You can try updating the `matplotlib` package or checking their repo as this appears to be an issue that sometimes occurs on Mac computers [according to their Issues](https://github.com/matplotlib/matplotlib/issues/18953).

Also, as a note, `AudioScheduler` is from another package and, while it is totally possible that it will function, I make no explicit guarantees for the usability of audio loaded with nodes outside MBM-Music-Visualizer.
